config/routes.rb
Chess::Application.routes.draw do
  devise_for :users, controllers: { :omniauth_callbacks => 'callbacks' }
  root 'static_pages#index'
  resources :games, :only => [:index, :new, :create, :show, :update] do
    resources :pieces, :only => [:create, :delete, :update]
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Team Fischer's Chess App</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <script src="https://cdn.firebase.com/js/client/2.2.5/firebase.js"></script>
  <%= csrf_meta_tags %>
</head>

<body class="Site">
<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '385815088277667',
      xfbml      : true,
      version    : 'v2.3'
    });
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>

<div class="Site-content">
  <nav class="navbar navbar-inverse" role="navigation">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
          <%= link_to 'Team Fischer' , root_path, :class => 'navbar-brand' %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
        	<li>
  		<% if user_signed_in? %>
  		  <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
  		<% else %>
  		  <li><%= link_to 'Sign in', new_user_session_path %></li>
  		<% end %>
        	</li>
          <li><%= link_to 'New Game' , games_path, :method => :post %></li>
          <li><%= link_to 'Join Game', games_path %></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <% if notice.present? %>
    <p class="alert alert-info"><%= notice %></p>
  <% end %>
  <% if alert.present? %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>

  <%= yield %>
</div>
<div class="row-fluid footer Site-footer">
  <% if user_signed_in? %>
    <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
  <% else %>
    <li><%= link_to 'Sign in', new_user_session_path %></li>
  <% end %>
</div>

</body>

</html>